#version: "3.9"
services:
  management-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: management-app
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - management-db
    networks:
      - management_net
    restart: unless-stopped

  management-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: management-worker
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - management-app
    networks:
      - management_net
    restart: unless-stopped

  management-nginx:
    image: nginx:1.25-alpine
    container_name: management-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - management-app
    networks:
      - management_net
    restart: unless-stopped

  management-db:
    image: mariadb:11.2
    container_name: management-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_DATABASE:-management}
      MYSQL_USER: ${DB_USERNAME:-management}
      MYSQL_PASSWORD: ${DB_PASSWORD:-managementpass}
    ports:
      - "3308:3306"
    volumes:
      - management_db_data:/var/lib/mysql
    networks:
      - management_net
    restart: unless-stopped

  management-phpmyadmin:
    image: phpmyadmin:5.2
    container_name: management-phpmyadmin
    environment:
      PMA_HOST: management-db
      PMA_USER: ${DB_USERNAME:-management}
      PMA_PASSWORD: ${DB_PASSWORD:-managementpass}
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    depends_on:
      - management-db
    networks:
      - management_net
    restart: unless-stopped

volumes:
  management_db_data:

networks:
  management_net:
    driver: bridge
